增加免翻墙访问设置
NateScarlet/pixiv pull request #9
Opened 2020-09-14 08:48 UTC by captavia

2020-09-14 18:00 UTC, NateScarlet commented
这个功能我觉得应该用 htttp.RoundTripper 实现吧
而且作为库错误应该返回而不是打印

2020-09-15 03:23 UTC, NateScarlet requested changes

2020-09-15 10:15 UTC, captavia commented on pkg/artwork/artwork_test.go
> -	assert.Equal(t, "https://www.pixiv.net/artworks/22238487", i.URL().String())
我看了下pixivpy的免代理，差不多就是请求cloudflare获取pixiv的ip，然后请求ip加接口这样，整个链接就变成ip/api了，上面的全局配置算是因为要设置Request的host的内容。RoundTripper 这个我之前没了解过，我先去看看

2020-09-15 10:38 UTC, NateScarlet commented on pkg/artwork/artwork_test.go
> -	assert.Equal(t, "https://www.pixiv.net/artworks/22238487", i.URL().String())
那换到你这个实现会导致没法获得可用的URL 我是自己RSS收集器用 生成订阅源的时候要提供可点击的超链接

这个方法不是用的请求 Host 而是 Client.ServerURL
我的建议是加一个 Client.ServerIP 字段 请求的时候如果有IP就用IP 但是提供URL的方法还是用ServerURL
这样也不需要全局bypass来启用免代理了

2020-09-15 10:38 UTC, NateScarlet commented on pkg/artwork/artwork_test.go
> -	assert.Equal(t, "https://www.pixiv.net/artworks/22238487", i.URL().String())
而且这样还可以由使用者来决定用什么 DNS 或者直接环境变量设置固定值

2020-09-15 10:47 UTC, NateScarlet commented on pkg/artwork/artwork_test.go
> -	assert.Equal(t, "https://www.pixiv.net/artworks/22238487", i.URL().String())
如果用RoundTripper的话 可直接把IP设置在 RoundTripper 上
这样Client 不需要做任何改动 最多是加一个快捷设置RoundTripper的方法

2020-09-15 12:40 UTC, closed without merging

2020-09-15 12:41 UTC, NateScarlet commented
我自己用 RoundTripper 实现了……

2020-09-15 12:48 UTC, captavia commented
太强了，其实我刚刚在想可以在get那里判断Client.ServerIP然后把www.pixiv.net替换了哈哈哈哈

2020-09-15 17:18 UTC, NateScarlet commented
v0.3.4 加了TLS证书检查和可配置DNS
我已经把我的RSS收集器依赖更新了